
# 🐼 03 — Pandas

### A complete, self-contained beginner's notebook

This notebook explains **Pandas** from scratch — no prior file or resource needed.
Every term is explained in plain English, and every code cell has already been run so you can see the real output right away.

---

## What is Pandas?

**Pandas** is a Python **Library** built specifically for working with tables of data.

> 🧠 *Think of Pandas as an Excel spreadsheet you can control entirely with code — sort it, filter it, calculate with it, clean it, all in a few lines.*

Pandas is built on top of **NumPy**, so a lot of the array ideas from `02_NumPy.ipynb` (indexing, slicing, vectorization) carry over directly.

---

## What this notebook covers

1. Series vs DataFrame
2. Creating a DataFrame
3. Exploring a dataset (head, shape, info, dtypes)
4. Selecting columns & rows (`loc` and `iloc`)
5. Filtering with conditions
6. Adding, modifying & dropping columns
7. Handling missing data (NaN)
8. Descriptive statistics
9. Sorting, duplicates & unique values
10. GroupBy
11. Merging, joining & concatenating tables
12. Pivot tables
13. Apply & map — custom functions on data
14. Reading & writing CSV files
15. Quick-reference glossary
16. Practice exercises


## 🔧 Setup

In [1]:

import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("Setup complete! ✅")

Pandas version: 3.0.2
Setup complete! ✅


---
## 1️⃣ Series vs DataFrame

| Term | Definition | Real-life example |
|---|---|---|
| **Series** | A single column of data with labels | Just the "Marks" column on its own |
| **DataFrame** | A full table with rows and columns | An entire class record sheet |

In [2]:

# A Pandas Series: a single labeled column
marks_series = pd.Series([85, 90, 76, 60, 95], name="Marks")
print("A Pandas Series:")
print(marks_series)
print("\nType:", type(marks_series))

A Pandas Series:
0    85
1    90
2    76
3    60
4    95
Name: Marks, dtype: int64

Type: <class 'pandas.Series'>

In [3]:

# A Series with custom labels (Index) instead of default 0,1,2...
custom_series = pd.Series([85, 90, 76], index=["Ali", "Sara", "Zain"], name="Marks")
print("Series with custom Index (student names):")
print(custom_series)

Series with custom Index (student names):
Ali     85
Sara    90
Zain    76
Name: Marks, dtype: int64


---
## 2️⃣ Creating a DataFrame

A **DataFrame** is Pandas' main structure — a table made of rows and columns.

We'll build one **Dataset** (a collection of related data) about students, and use it throughout this notebook.

- **Data** = the raw facts/numbers themselves
- **Feature** = a single measurable column (e.g. "Age", "Marks")
- **Column** = a vertical set of values
- **Row** = a horizontal set of values — one full record

In [4]:

data = {
    "Name":   ["Ali", "Sara", "Zain", "Mina", "Bilal", "Hina", "Omar", "Noor"],
    "Age":    [20, 21, 19, 22, 20, 23, 21, np.nan],       # np.nan = missing value
    "City":   ["Lahore", "Karachi", "Lahore", "Islamabad", "Karachi", "Lahore", "Multan", "Karachi"],
    "Marks":  [85, 90, 76, 60, 95, 88, 72, 81],
    "Subject":["Math", "Science", "Math", "Art", "Science", "Math", "Art", "Science"]
}

df = pd.DataFrame(data)
df

    Name   Age       City  Marks  Subject
0    Ali  20.0     Lahore     85     Math
1   Sara  21.0    Karachi     90  Science
2   Zain  19.0     Lahore     76     Math
3   Mina  22.0  Islamabad     60      Art
4  Bilal  20.0    Karachi     95  Science
5   Hina  23.0     Lahore     88     Math
6   Omar  21.0     Multan     72      Art
7   Noor   NaN    Karachi     81  Science


---
## 3️⃣ Exploring a Dataset

Always look at your data before working with it.

- **Head** = viewing just the first few rows
- **Shape** = size of data in (rows, columns)
- **Index** = the row labels
- **Data Type** = the kind of value each column holds

In [5]:

print("First 3 rows (head):")
display(df.head(3))

print("\nLast 2 rows (tail):")
display(df.tail(2))

print("\nShape (rows, columns):", df.shape)
print("Column names:", df.columns.tolist())
print("Index (row labels):", df.index.tolist())

First 3 rows (head):

   Name   Age     City  Marks  Subject
0   Ali  20.0   Lahore     85     Math
1  Sara  21.0  Karachi     90  Science
2  Zain  19.0   Lahore     76     Math

Last 2 rows (tail):

   Name   Age     City  Marks  Subject
6  Omar  21.0   Multan     72      Art
7  Noor   NaN  Karachi     81  Science

Shape (rows, columns): (8, 5)
Column names: ['Name', 'Age', 'City', 'Marks', 'Subject']
Index (row labels): [0, 1, 2, 3, 4, 5, 6, 7]

In [6]:

print("Data types of each column:")
print(df.dtypes)

print("\nFull structural summary:")
df.info()

Data types of each column:
Name           str
Age        float64
City           str
Marks        int64
Subject        str
dtype: object

Full structural summary:
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     8 non-null      str
 1   Age      7 non-null      float64
 2   City     8 non-null      str
 3   Marks    8 non-null      int64
 4   Subject  8 non-null      str
dtypes: float64(1), int64(1), str(3)
memory usage: 452.0 bytes


---
## 4️⃣ Selecting Columns & Rows (`loc` and `iloc`)

- **`loc`** = select by **label** (column name, index label)
- **`iloc`** = select by **position** (numeric location, like array indexing)

In [7]:

# Selecting a single column (returns a Series)
print("Just the 'Name' column:")
print(df["Name"])

Just the 'Name' column:
0      Ali
1     Sara
2     Zain
3     Mina
4    Bilal
5     Hina
6     Omar
7     Noor
Name: Name, dtype: str

In [8]:

# Selecting multiple columns
print("Name and Marks columns together:")
df[["Name", "Marks"]]

Name and Marks columns together:

    Name  Marks
0    Ali     85
1   Sara     90
2   Zain     76
3   Mina     60
4  Bilal     95
5   Hina     88
6   Omar     72
7   Noor     81

In [9]:

# loc: select rows by label, and specific columns
print("Using loc — rows 0 to 2, only Name & Marks columns:")
df.loc[0:2, ["Name", "Marks"]]

Using loc — rows 0 to 2, only Name & Marks columns:

   Name  Marks
0   Ali     85
1  Sara     90
2  Zain     76

In [10]:

# iloc: select rows and columns purely by position (like a 2D array)
print("Using iloc — first 3 rows, first 2 columns:")
df.iloc[0:3, 0:2]

Using iloc — first 3 rows, first 2 columns:

   Name   Age
0   Ali  20.0
1  Sara  21.0
2  Zain  19.0

In [11]:

# Slice: taking a smaller piece of the DataFrame
first_four_students = df[0:4]
print("Slice — first four students:")
first_four_students

Slice — first four students:

   Name   Age       City  Marks  Subject
0   Ali  20.0     Lahore     85     Math
1  Sara  21.0    Karachi     90  Science
2  Zain  19.0     Lahore     76     Math
3  Mina  22.0  Islamabad     60      Art


---
## 5️⃣ Filtering With Conditions

- **Boolean** = a value that is `True` or `False`
- **Filter** = keeping only rows that match a condition

In [12]:

# Boolean mask: which students scored above 80?
above_80 = df["Marks"] > 80
print("Boolean mask:")
print(above_80)

Boolean mask:
0     True
1     True
2    False
3    False
4     True
5     True
6    False
7     True
Name: Marks, dtype: bool

In [13]:

# Filter: use the mask to keep only matching rows
top_students = df[df["Marks"] > 80]
print("Students who scored above 80:")
top_students

Students who scored above 80:

    Name   Age     City  Marks  Subject
0    Ali  20.0   Lahore     85     Math
1   Sara  21.0  Karachi     90  Science
4  Bilal  20.0  Karachi     95  Science
5   Hina  23.0   Lahore     88     Math
7   Noor   NaN  Karachi     81  Science

In [14]:

# Combining multiple conditions with & (and) / | (or)
# Students from Karachi AND scored above 80
karachi_top = df[(df["City"] == "Karachi") & (df["Marks"] > 80)]
print("Students from Karachi who scored above 80:")
karachi_top

Students from Karachi who scored above 80:

    Name   Age     City  Marks  Subject
1   Sara  21.0  Karachi     90  Science
4  Bilal  20.0  Karachi     95  Science
7   Noor   NaN  Karachi     81  Science

In [15]:

# Query: asking a question of your data using a readable string
result = df.query("Marks > 85 and City == 'Karachi'")
print("Using .query() — same kind of question, more readable:")
result

Using .query() — same kind of question, more readable:

    Name   Age     City  Marks  Subject
1   Sara  21.0  Karachi     90  Science
4  Bilal  20.0  Karachi     95  Science


---
## 6️⃣ Adding, Modifying & Dropping Columns

In [16]:

df2 = df.copy()

# Adding a new column: Pass/Fail based on Marks
df2["Pass"] = df2["Marks"] >= 75
print("Added a new 'Pass' column:")
df2

Added a new 'Pass' column:

    Name   Age       City  Marks  Subject   Pass
0    Ali  20.0     Lahore     85     Math   True
1   Sara  21.0    Karachi     90  Science   True
2   Zain  19.0     Lahore     76     Math   True
3   Mina  22.0  Islamabad     60      Art  False
4  Bilal  20.0    Karachi     95  Science   True
5   Hina  23.0     Lahore     88     Math   True
6   Omar  21.0     Multan     72      Art  False
7   Noor   NaN    Karachi     81  Science   True

In [17]:

# Modifying an existing column: add 2 bonus marks to everyone (vectorized, no loop)
df2["Marks"] = df2["Marks"] + 2
print("Marks column after adding 2 bonus marks to everyone:")
df2[["Name", "Marks"]]

Marks column after adding 2 bonus marks to everyone:

    Name  Marks
0    Ali     87
1   Sara     92
2   Zain     78
3   Mina     62
4  Bilal     97
5   Hina     90
6   Omar     74
7   Noor     83

In [18]:

# Dropping a column we no longer need
df2 = df2.drop(columns=["Pass"])
print("After dropping the 'Pass' column:")
df2

After dropping the 'Pass' column:

    Name   Age       City  Marks  Subject
0    Ali  20.0     Lahore     87     Math
1   Sara  21.0    Karachi     92  Science
2   Zain  19.0     Lahore     78     Math
3   Mina  22.0  Islamabad     62      Art
4  Bilal  20.0    Karachi     97  Science
5   Hina  23.0     Lahore     90     Math
6   Omar  21.0     Multan     74      Art
7   Noor   NaN    Karachi     83  Science


---
## 7️⃣ Handling Missing Data (NaN)

**NaN** = "Not a Number" — represents missing or unknown data.

> 🧠 *If a student didn't attend an exam, their score might be recorded as NaN instead of a number.*

In [19]:

print("Which cells are missing?")
print(df.isna())

print("\nNumber of missing values per column:")
print(df.isna().sum())

Which cells are missing?
    Name    Age   City  Marks  Subject
0  False  False  False  False    False
1  False  False  False  False    False
2  False  False  False  False    False
3  False  False  False  False    False
4  False  False  False  False    False
5  False  False  False  False    False
6  False  False  False  False    False
7  False   True  False  False    False

Number of missing values per column:
Name       0
Age        1
City       0
Marks      0
Subject    0
dtype: int64

In [20]:

# Option 1: fill missing values (e.g. with the column mean)
df_filled = df.copy()
df_filled["Age"] = df_filled["Age"].fillna(df_filled["Age"].mean())
print("Age column after filling the missing value with the mean:")
df_filled

Age column after filling the missing value with the mean:

    Name        Age       City  Marks  Subject
0    Ali  20.000000     Lahore     85     Math
1   Sara  21.000000    Karachi     90  Science
2   Zain  19.000000     Lahore     76     Math
3   Mina  22.000000  Islamabad     60      Art
4  Bilal  20.000000    Karachi     95  Science
5   Hina  23.000000     Lahore     88     Math
6   Omar  21.000000     Multan     72      Art
7   Noor  20.857143    Karachi     81  Science

In [21]:

# Option 2: drop rows that have any missing values
df_dropped = df.dropna()
print("After dropping rows with missing values:")
df_dropped

After dropping rows with missing values:

    Name   Age       City  Marks  Subject
0    Ali  20.0     Lahore     85     Math
1   Sara  21.0    Karachi     90  Science
2   Zain  19.0     Lahore     76     Math
3   Mina  22.0  Islamabad     60      Art
4  Bilal  20.0    Karachi     95  Science
5   Hina  23.0     Lahore     88     Math
6   Omar  21.0     Multan     72      Art


---
## 8️⃣ Descriptive Statistics

| Term | Definition |
|---|---|
| **Mean** | The average |
| **Median** | The middle value when sorted |
| **Mode** | The most frequent value |
| **Standard Deviation** | How spread out numbers are from the average |

In [22]:

marks = df["Marks"]

print("Mean:", marks.mean())
print("Median:", marks.median())
print("Mode:", marks.mode()[0])
print("Standard Deviation:", round(marks.std(), 2))
print("Min:", marks.min(), "| Max:", marks.max())

Mean: 80.875
Median: 83.0
Mode: 60
Standard Deviation: 11.27
Min: 60 | Max: 95

In [23]:

# describe() gives all key stats in one shot
print("Full statistical summary of numeric columns:")
df.describe()

Full statistical summary of numeric columns:

             Age      Marks
count   7.000000   8.000000
mean   20.857143  80.875000
std     1.345185  11.268635
min    19.000000  60.000000
25%    20.000000  75.000000
50%    21.000000  83.000000
75%    21.500000  88.500000
max    23.000000  95.000000


---
## 9️⃣ Sorting, Duplicates & Unique Values

- **Duplicate** = a row/value that appears more than once
- **Unique** = values that appear only once, no repeats

In [24]:

sorted_df = df.sort_values(by="Marks", ascending=False)
print("Sorted by Marks (highest first):")
sorted_df

Sorted by Marks (highest first):

    Name   Age       City  Marks  Subject
4  Bilal  20.0    Karachi     95  Science
1   Sara  21.0    Karachi     90  Science
5   Hina  23.0     Lahore     88     Math
0    Ali  20.0     Lahore     85     Math
7   Noor   NaN    Karachi     81  Science
2   Zain  19.0     Lahore     76     Math
6   Omar  21.0     Multan     72      Art
3   Mina  22.0  Islamabad     60      Art

In [25]:

unique_cities = df["City"].unique()
print("Unique cities:", unique_cities)

value_counts = df["City"].value_counts()
print("\nHow many students per city:")
print(value_counts)

Unique cities: <StringArray>
['Lahore', 'Karachi', 'Islamabad', 'Multan']
Length: 4, dtype: str

How many students per city:
City
Lahore       3
Karachi      3
Islamabad    1
Multan       1
Name: count, dtype: int64

In [26]:

print("Duplicate rows found:", df.duplicated().sum())

demo_df = pd.concat([df, df.iloc[[0]]], ignore_index=True)  # copy Ali's row again
print("After adding a duplicate row on purpose:", demo_df.duplicated().sum(), "duplicate(s) found")

Duplicate rows found: 0

After adding a duplicate row on purpose: 1 duplicate(s) found


---
## 🔟 GroupBy

**GroupBy** = splitting data into groups based on a value, so you can summarize each group.

> 🧠 *Grouping students by "City" to find the average marks in each city.*

In [27]:

avg_marks_by_city = df.groupby("City")["Marks"].mean()
print("Average marks per city:")
avg_marks_by_city

Average marks per city:

City
Islamabad    60.000000
Karachi      88.666667
Lahore       83.000000
Multan       72.000000
Name: Marks, dtype: float64

In [28]:

city_subject_summary = df.groupby(["City", "Subject"])["Marks"].mean()
print("Average marks per city, broken down by subject:")
city_subject_summary

Average marks per city, broken down by subject:

City       Subject
Islamabad  Art        60.000000
Karachi    Science    88.666667
Lahore     Math       83.000000
Multan     Art        72.000000
Name: Marks, dtype: float64

In [29]:

# Multiple statistics at once per group
summary = df.groupby("City")["Marks"].agg(["mean", "min", "max", "count"])
print("Full summary of marks per city:")
summary

Full summary of marks per city:

                mean  min  max  count
City
Islamabad  60.000000   60   60      1
Karachi    88.666667   81   95      3
Lahore     83.000000   76   88      3
Multan     72.000000   72   72      1


---
## 1️⃣1️⃣ Merging, Joining & Concatenating Tables

- **Join** = combining two tables using a shared column
- **Key** = the column used to match rows between tables

> 🧠 *Merging a "Student Info" table with a "Student Attendance" table using "RollNo" they both share.*

In [30]:

student_info = pd.DataFrame({
    "RollNo": [1, 2, 3, 4],
    "Name":   ["Ali", "Sara", "Zain", "Mina"]
})

attendance = pd.DataFrame({
    "RollNo": [1, 2, 3, 4],
    "AttendancePercent": [95, 88, 76, 99]
})

merged = pd.merge(student_info, attendance, on="RollNo")
print("Merged table (joined using 'RollNo' as the key):")
merged

Merged table (joined using 'RollNo' as the key):

   RollNo  Name  AttendancePercent
0       1   Ali                 95
1       2  Sara                 88
2       3  Zain                 76
3       4  Mina                 99

In [31]:

# Concatenate: stacking two tables with the SAME columns on top of each other
batch_1 = pd.DataFrame({"Name": ["Ali", "Sara"], "Marks": [85, 90]})
batch_2 = pd.DataFrame({"Name": ["Zain", "Mina"], "Marks": [76, 60]})

all_batches = pd.concat([batch_1, batch_2], ignore_index=True)
print("Concatenated (stacked) tables:")
all_batches

Concatenated (stacked) tables:

   Name  Marks
0   Ali     85
1  Sara     90
2  Zain     76
3  Mina     60


---
## 1️⃣2️⃣ Pivot Tables

**Pivot Table** = a table that summarizes and rearranges data to see patterns easily.

> 🧠 *Turning a long list of records into a summary showing average marks per city per subject.*

In [32]:

pivot = df.pivot_table(values="Marks", index="City", columns="Subject", aggfunc="mean")
print("Pivot table — average marks by City and Subject:")
pivot

Pivot table — average marks by City and Subject:

Subject     Art  Math    Science
City
Islamabad  60.0   NaN        NaN
Karachi     NaN   NaN  88.666667
Lahore      NaN  83.0        NaN
Multan     72.0   NaN        NaN


---
## 1️⃣3️⃣ Apply & Map — Custom Functions on Data

- **Function** = a reusable block of instructions that performs a task
- `.apply()` lets you run your own custom function on every value in a column
- `.map()` is a simpler version, often used for direct value substitutions

In [33]:

# A custom Function: convert marks into a Grade
def marks_to_grade(marks):
    if marks >= 90:
        return "A"
    elif marks >= 75:
        return "B"
    elif marks >= 60:
        return "C"
    else:
        return "F"

df3 = df.copy()
df3["Grade"] = df3["Marks"].apply(marks_to_grade)
print("Added a 'Grade' column using a custom function with .apply():")
df3[["Name", "Marks", "Grade"]]

Added a 'Grade' column using a custom function with .apply():

    Name  Marks Grade
0    Ali     85     B
1   Sara     90     A
2   Zain     76     B
3   Mina     60     C
4  Bilal     95     A
5   Hina     88     B
6   Omar     72     C
7   Noor     81     B

In [34]:

# .map() for simple value substitution
city_short_codes = {"Lahore": "LHR", "Karachi": "KHI", "Islamabad": "ISB", "Multan": "MUX"}
df3["CityCode"] = df3["City"].map(city_short_codes)
print("Added a 'CityCode' column using .map():")
df3[["Name", "City", "CityCode"]]

Added a 'CityCode' column using .map():

    Name       City CityCode
0    Ali     Lahore      LHR
1   Sara    Karachi      KHI
2   Zain     Lahore      LHR
3   Mina  Islamabad      ISB
4  Bilal    Karachi      KHI
5   Hina     Lahore      LHR
6   Omar     Multan      MUX
7   Noor    Karachi      KHI


---
## 1️⃣4️⃣ Reading & Writing CSV Files

**CSV** = "Comma-Separated Values" — a simple text file format for tables, like a basic spreadsheet.

In [35]:

# Save our DataFrame to a CSV file
df.to_csv("students_pandas.csv", index=False)
print("Saved to students_pandas.csv ✅")

# Read it back
df_from_csv = pd.read_csv("students_pandas.csv")
print("\nData read back from CSV:")
df_from_csv

Saved to students_pandas.csv ✅

Data read back from CSV:

    Name   Age       City  Marks  Subject
0    Ali  20.0     Lahore     85     Math
1   Sara  21.0    Karachi     90  Science
2   Zain  19.0     Lahore     76     Math
3   Mina  22.0  Islamabad     60      Art
4  Bilal  20.0    Karachi     95  Science
5   Hina  23.0     Lahore     88     Math
6   Omar  21.0     Multan     72      Art
7   Noor   NaN    Karachi     81  Science


---
## 📖 Quick-Reference Glossary Recap

| Term | Simple Definition |
|---|---|
| Boolean | A True/False value |
| Column | A vertical set of values (one feature) |
| CSV | Comma-separated text file format for tables |
| DataFrame | A full table with rows & columns |
| Data Type | The kind of value stored (number, text, boolean) |
| Dataset | A collection of related data |
| Duplicate | A row/value that appears more than once |
| Feature | A single measurable column |
| Filter | Selecting rows that match a condition |
| Function | A reusable block of instructions |
| GroupBy | Splitting data into groups to summarize each |
| Head | Viewing the first few rows |
| Index | The row labels |
| Join | Combining two tables using a shared column |
| Key | Column used to match/identify rows |
| Mean | The average |
| Median | The middle value when sorted |
| Mode | The most frequent value |
| NaN | Missing or unknown data |
| Pandas | Library for working with tables of data |
| Pivot Table | Rearranged summary table |
| Query | A question asked of your data |
| Row | A horizontal set of values (one record) |
| Series | A single labeled column of data |
| Shape | Size of data as (rows, columns) |
| Slice | A smaller piece taken from a table |
| Standard Deviation | How spread out values are from the mean |
| Unique | Values with no repeats |


---
## ✏️ Practice Exercises

Try these yourself using the `df` DataFrame from earlier, before checking the solutions.

1. Show only students studying "Math".
2. Add a new column "AboveAverage" that is `True` if a student's marks are above the class average.
3. Find the city with the highest average marks.
4. Create a pivot table showing the count of students per city.

In [36]:

# 1. Students studying Math
print("Exercise 1 — Students studying Math:")
print(df[df["Subject"] == "Math"])

Exercise 1 — Students studying Math:
   Name   Age    City  Marks Subject
0   Ali  20.0  Lahore     85    Math
2  Zain  19.0  Lahore     76    Math
5  Hina  23.0  Lahore     88    Math

In [37]:

# 2. AboveAverage column
df_ex = df.copy()
class_average = df_ex["Marks"].mean()
df_ex["AboveAverage"] = df_ex["Marks"] > class_average
print("Exercise 2 — Class average:", round(class_average, 2))
df_ex[["Name", "Marks", "AboveAverage"]]

Exercise 2 — Class average: 80.88

    Name  Marks  AboveAverage
0    Ali     85          True
1   Sara     90          True
2   Zain     76         False
3   Mina     60         False
4  Bilal     95          True
5   Hina     88          True
6   Omar     72         False
7   Noor     81          True

In [38]:

# 3. City with highest average marks
avg_by_city = df.groupby("City")["Marks"].mean()
best_city = avg_by_city.idxmax()
print("Exercise 3 — Average marks per city:")
print(avg_by_city)
print("\nCity with the highest average marks:", best_city)

Exercise 3 — Average marks per city:
City
Islamabad    60.000000
Karachi      88.666667
Lahore       83.000000
Multan       72.000000
Name: Marks, dtype: float64

City with the highest average marks: Karachi

In [39]:

# 4. Pivot table: count of students per city
count_pivot = df.pivot_table(values="Name", index="City", aggfunc="count")
print("Exercise 4 — Number of students per city:")
count_pivot

Exercise 4 — Number of students per city:

           Name
City
Islamabad     1
Karachi       3
Lahore        3
Multan        1


---
## 🎯 Conclusion & Next Steps

You've now covered the essential building blocks of Pandas:

✅ Series & DataFrames
✅ Exploring datasets
✅ Selecting with `loc`/`iloc`, slicing & filtering
✅ Adding, modifying & dropping columns
✅ Handling missing data
✅ Descriptive statistics
✅ Sorting, duplicates & unique values
✅ GroupBy
✅ Merging, joining & concatenating
✅ Pivot tables
✅ Apply & map for custom logic
✅ Reading/writing CSV files

### What to do next
- Move on to **04_Matplotlib.ipynb** to learn how to turn this kind of data into clear, beautiful charts.
- Try loading a real CSV dataset and repeating every step in this notebook on it.

**You don't need any other file to understand this notebook — everything was defined, explained, and demonstrated with real output above.**